### PR TITLE
generate only future dates and only if is_on_sale is true

### LINKED ISSUE #171: [Bug] - Date on sale to shouldnt set dates in the past
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

After setting up a fresh wordpress site i installed Woo and WC Smooth Generator and let it generate around 1k fake products.

Noticed on a quite a few products have quite old sale to dates. What i notice:
1) if no sale price is set setting a sale to price doesnt make sense
2) date shouldnt be in the past

Few examples on **simple** products:
1) Image
2)  Image

See codepart: https://github.com/woocommerce/wc-smooth-generator/blob/trunk/includes/Generator/Product.php#L389C4-L389C90

Same happens also on **variable** products:
Image

### WordPress Environment

_No response_

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce and WooCommerce Smooth Generator plugins are active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by masteradhoc**
### All Submissions:

* [x] Have you followed the [Contributing guidelines](https://github.com/woocommerce/wc-smooth-generator/blob/trunk/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/wc-smooth-generator/pulls) for the same update/change?

### Changes proposed in this Pull Request:
"date_on_sale" shouldnt generate past dates and only generate if the product is actually on sale (sale price is set)

Closes #171.

### How to test the changes in this Pull Request:

1. apply the pr
2. generate some products
3. check if for not on sale products the sale to date is set - if not good
4. check if for on sale product the sale to date is in the future - if yes good

### Screenshots
image
image

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

### Changelog entry
Make sure "date_sale_to" only generate future dates
Make sure "date_sale_to" is only set if the product is on sale
> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

### FOR PR REVIEWER ONLY:

* [x] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Comment by masteradhoc** [comment]
@layoutd can you check this PR and see if any changes are needed to get it merged? :)

File: includes/Generator/Product.php [hunk 1]
```diff
@@ -337,7 +337,7 @@ protected static function generate_variable_product() {
 				'regular_price'     => $price,
 				'sale_price'        => $sale_price,
 				'date_on_sale_from' => '',
-				'date_on_sale_to'   => self::$faker->iso8601( date( 'c', strtotime( '+1 month' ) ) ),
+				'date_on_sale_to' 	=> $is_on_sale ? self::$faker->dateTimeBetween('now', '+1 month')->format(DATE_ATOM) : '',
```
Comment (layoutd) [inline includes/Generator/Product.php]:
```suggestion
				'date_on_sale_to'   => $is_on_sale ? self::$faker->dateTimeBetween( 'now', '+1 month' )->format( DATE_ATOM ) : '',
```

File: includes/Generator/Product.php [hunk 2]
```diff
@@ -386,7 +386,7 @@ protected static function generate_simple_product() {
 			'regular_price'      => $price,
 			'sale_price'         => $sale_price,
 			'date_on_sale_from'  => '',
-			'date_on_sale_to'    => self::$faker->iso8601( date( 'c', strtotime( '+1 month' ) ) ),
+			'date_on_sale_to'    => $is_on_sale ? self::$faker->dateTimeBetween('now', '+1 month')->format(DATE_ATOM) : '',
```
Comment (layoutd) [inline includes/Generator/Product.php]:
```suggestion
			'date_on_sale_to'    => $is_on_sale ? self::$faker->dateTimeBetween( 'now', '+1 month' )->format( DATE_ATOM ) : '',
```

**Review by layoutd — APPROVED** [review]
Works as indicated. I left a few spacing fixes.

Do you think it would make sense to also randomly decide whether to assign an end date. E.g., some products on clearance with a permanent price reduction?

**Comment by masteradhoc** [comment]
Thanks @layoutd accepted your suggestions and resolved some merge conflicts!

_Do you think it would make sense to also randomly decide whether to assign an end date. E.g., some products on clearance with a permanent price reduction?_
Great suggestion. i went ahead and introduced a variable that decides for 40% of the on sale products that the sale prices should be scheduled. rest will be infinite.

What do you think?

**Comment by layoutd** [comment]
LGTM 🚢  Thanks @masteradhoc
